### ISSUE TITLE
[REQUEST] Name and Id area

### ISSUE THREAD

**Issue by fatihbahceci** [StartBootstrap/sb-form-builder-feedback#3]
I'll use this form for post data to my API. So it's requires element name for parsing data. 
Also I don't need the Id forehead on most of my forms, so I think Name and Id must be optional and customizable.

**Comment by initplatform** [comment]
Hi,

Form Builder was created as a companion to our forms service. 

<https://startbootstrap.com/solution/contact-forms>

You are certainly welcome to use it to generate forms for your own apis, but as you mentioned,
you will need to modify the generated html to fit your particular needs. 

All the best!

./sam

**Comment by fatihbahceci** [comment]
By the way, thanks a lot. Your app is very useful and makes things very easy.
